services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=ConwaysGameOfLife
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "6831:6831/udp"
  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5431:80"
    environment:
      - ACCEPT_EULA=Y
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  
  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.108.0
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "8090"
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - jaeger
      - seq
      - prometheus

volumes:
  postgres_data:
    name: postgres_data
    external: false