name: Request Code Review

on:
  pull_request:
    types: [labeled]

jobs:
  request:
    if: ${{ github.event.label.name == 'request-review' }}
    name: Request Review on Discord
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: mitz-it/discord-message-action@v1
        with:
          token: ${{ secrets.DISCORD_BOT_TOKEN }}
          channel-id: ${{ secrets.DISCORD_PR_CHANNEL_ID }}
          message-content: "https://github.com/lgcmotta/GQS2025-1-A3-conways-game-of-life/pull/${{ github.event.pull_request.number }}"
