name: Build and Publish Image to GitHub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Build & Push to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ulife/a3/conways-game-of-life
          tags: |
            type=semver,enable=true,pattern={{version}}
            type=sha,enable=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          file: ./src/Conways.GameOfLife.API/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}